export const basketReducerTypes = {
    ADD_TO_BASKET: 'ADD_TO_BASKET',
    REMOVE_FROM_BASKET: 'REMOVE_FROM_BASKET',
    EMPTY_BASKET: 'EMPTY_BASKET'
}

export const displayReducerTypes = {
    OPEN_MY_ACCOUNT_POPOVER: 'OPEN_MY_ACCOUNT_POPOVER',
    CLOSE_POPOVER: 'CLOSE_POPOVER',
}